### ISSUE TITLE
Can I change min, max value dynamically? 

### ISSUE THREAD

**Issue by jjhok** [shushutochako/CircleSlider#2]
How can I change min, max value (or other option values) dynamically?

**Comment by shushutochako** [comment]
Hi @jjhok .
Does that mean you want to change options after instantiation?
It is currently not implemented.
I want to support in the near future, because I think also need.

**Comment by heshanlk** [comment]
This is a nice to have a feature. In addition to that if we can change the color etc it will be really helpful too.

**Comment by shushutochako** [comment]
@jjhok 
It added support to be changing the option after instantiation.
Please use the version 0.2.0

**Comment by heshanlk** [comment]
Nice, thanks

**Comment by shushutochako** [comment]
@heshanlk 
Likewise. Thank you for your advice.

**Comment by shushutochako** [comment]
Close due to the corresponding.
https://github.com/shushutochako/CircleSlider/pull/3
